using System.Text;
using System.Linq;
using OrmLib.Metadata;

namespace OrmLib.Sql;

/// <summary>
/// Builds PostgreSQL INSERT SQL statements.
/// </summary>
public static class InsertSqlBuilder
{
    /// <summary>
    /// Generates an INSERT statement for the specified table metadata.
    /// Excludes auto-increment primary key columns from the INSERT.
    /// </summary>
    /// <param name="tableMetadata">The table metadata.</param>
    /// <returns>A tuple containing the SQL statement and the list of columns to insert (excluding auto-increment PK).</returns>
    public static (string Sql, IReadOnlyList<ColumnMetadata> Columns) BuildInsert(TableMetadata tableMetadata)
    {
        if (tableMetadata == null)
            throw new ArgumentNullException(nameof(tableMetadata));

        // Exclude auto-increment primary key columns (they're generated by the database)
        var columnsToInsert = tableMetadata.Columns
            .Where(c => !(c.IsPrimaryKey && c.IsAutoIncrement))
            .ToList();

        if (columnsToInsert.Count == 0)
        {
            throw new InvalidOperationException($"Table {tableMetadata.TableName} has no columns to insert (all columns are auto-increment primary keys).");
        }

        var sql = new StringBuilder();
        sql.Append($"INSERT INTO \"{tableMetadata.TableName}\" (");

        var columnNames = columnsToInsert.Select(c => $"\"{c.ColumnName}\"").ToList();
        sql.Append(string.Join(", ", columnNames));

        sql.Append(") VALUES (");

        // Use parameterized queries with @p1, @p2... format for Npgsql compatibility
        var parameters = new List<string>();
        for (int i = 0; i < columnsToInsert.Count; i++)
        {
            parameters.Add($"@p{i + 1}");
        }

        sql.Append(string.Join(", ", parameters));
        sql.Append(")");

        // Add RETURNING clause for auto-increment primary keys
        if (tableMetadata.PrimaryKey.IsAutoIncrement)
        {
            sql.Append($" RETURNING \"{tableMetadata.PrimaryKey.ColumnName}\"");
        }

        return (sql.ToString(), columnsToInsert);
    }
}

